// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source auth.go -destination mock/auth.go -package mock
//

// Package mock is a generated GoMock package.
package mock
