// Code generated by MockGen. DO NOT EDIT.
// Source: action_module.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth0 "github.com/auth0/auth0-cli/internal/auth0"
	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockActionModuleAPIV3 is a mock of ActionModuleAPIV3 interface.
type MockActionModuleAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockActionModuleAPIV3MockRecorder
}

// MockActionModuleAPIV3MockRecorder is the mock recorder for MockActionModuleAPIV3.
type MockActionModuleAPIV3MockRecorder struct {
	mock *MockActionModuleAPIV3
}

// NewMockActionModuleAPIV3 creates a new mock instance.
func NewMockActionModuleAPIV3(ctrl *gomock.Controller) *MockActionModuleAPIV3 {
	mock := &MockActionModuleAPIV3{ctrl: ctrl}
	mock.recorder = &MockActionModuleAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionModuleAPIV3) EXPECT() *MockActionModuleAPIV3MockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActionModuleAPIV3) Create(ctx context.Context, request *management.CreateActionModuleRequestContent, opts ...option.RequestOption) (*management.CreateActionModuleResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*management.CreateActionModuleResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockActionModuleAPIV3MockRecorder) Create(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActionModuleAPIV3)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockActionModuleAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActionModuleAPIV3MockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActionModuleAPIV3)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockActionModuleAPIV3) Get(ctx context.Context, id string, opts ...option.RequestOption) (*management.GetActionModuleResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetActionModuleResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockActionModuleAPIV3MockRecorder) Get(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockActionModuleAPIV3)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockActionModuleAPIV3) List(ctx context.Context, request *management.GetActionModulesRequestParameters, opts ...option.RequestOption) (*auth0.ActionModulePage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.ActionModulePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockActionModuleAPIV3MockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActionModuleAPIV3)(nil).List), varargs...)
}

// ListActions mocks base method.
func (m *MockActionModuleAPIV3) ListActions(ctx context.Context, id string, request *management.GetActionModuleActionsRequestParameters, opts ...option.RequestOption) (*auth0.ActionModuleActionPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListActions", varargs...)
	ret0, _ := ret[0].(*auth0.ActionModuleActionPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActions indicates an expected call of ListActions.
func (mr *MockActionModuleAPIV3MockRecorder) ListActions(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActions", reflect.TypeOf((*MockActionModuleAPIV3)(nil).ListActions), varargs...)
}

// Rollback mocks base method.
func (m *MockActionModuleAPIV3) Rollback(ctx context.Context, id string, request *management.RollbackActionModuleRequestParameters, opts ...option.RequestOption) (*management.RollbackActionModuleResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Rollback", varargs...)
	ret0, _ := ret[0].(*management.RollbackActionModuleResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rollback indicates an expected call of Rollback.
func (mr *MockActionModuleAPIV3MockRecorder) Rollback(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockActionModuleAPIV3)(nil).Rollback), varargs...)
}

// Update mocks base method.
func (m *MockActionModuleAPIV3) Update(ctx context.Context, id string, request *management.UpdateActionModuleRequestContent, opts ...option.RequestOption) (*management.UpdateActionModuleResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateActionModuleResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockActionModuleAPIV3MockRecorder) Update(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActionModuleAPIV3)(nil).Update), varargs...)
}

// MockActionModuleVersionAPIV3 is a mock of ActionModuleVersionAPIV3 interface.
type MockActionModuleVersionAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockActionModuleVersionAPIV3MockRecorder
}

// MockActionModuleVersionAPIV3MockRecorder is the mock recorder for MockActionModuleVersionAPIV3.
type MockActionModuleVersionAPIV3MockRecorder struct {
	mock *MockActionModuleVersionAPIV3
}

// NewMockActionModuleVersionAPIV3 creates a new mock instance.
func NewMockActionModuleVersionAPIV3(ctrl *gomock.Controller) *MockActionModuleVersionAPIV3 {
	mock := &MockActionModuleVersionAPIV3{ctrl: ctrl}
	mock.recorder = &MockActionModuleVersionAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionModuleVersionAPIV3) EXPECT() *MockActionModuleVersionAPIV3MockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActionModuleVersionAPIV3) Create(ctx context.Context, id string, opts ...option.RequestOption) (*management.CreateActionModuleVersionResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*management.CreateActionModuleVersionResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockActionModuleVersionAPIV3MockRecorder) Create(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActionModuleVersionAPIV3)(nil).Create), varargs...)
}

// Get mocks base method.
func (m *MockActionModuleVersionAPIV3) Get(ctx context.Context, id, versionID string, opts ...option.RequestOption) (*management.GetActionModuleVersionResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, versionID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetActionModuleVersionResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockActionModuleVersionAPIV3MockRecorder) Get(ctx, id, versionID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, versionID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockActionModuleVersionAPIV3)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockActionModuleVersionAPIV3) List(ctx context.Context, id string, request *management.GetActionModuleVersionsRequestParameters, opts ...option.RequestOption) (*auth0.ActionModuleVersionPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.ActionModuleVersionPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockActionModuleVersionAPIV3MockRecorder) List(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActionModuleVersionAPIV3)(nil).List), varargs...)
}
