// Code generated by MockGen. DO NOT EDIT.
// Source: client_grant.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth0 "github.com/auth0/auth0-cli/internal/auth0"
	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockClientGrantAPIV3 is a mock of ClientGrantAPIV3 interface.
type MockClientGrantAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockClientGrantAPIV3MockRecorder
}

// MockClientGrantAPIV3MockRecorder is the mock recorder for MockClientGrantAPIV3.
type MockClientGrantAPIV3MockRecorder struct {
	mock *MockClientGrantAPIV3
}

// NewMockClientGrantAPIV3 creates a new mock instance.
func NewMockClientGrantAPIV3(ctrl *gomock.Controller) *MockClientGrantAPIV3 {
	mock := &MockClientGrantAPIV3{ctrl: ctrl}
	mock.recorder = &MockClientGrantAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientGrantAPIV3) EXPECT() *MockClientGrantAPIV3MockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientGrantAPIV3) Create(ctx context.Context, request *management.CreateClientGrantRequestContent, opts ...option.RequestOption) (*management.CreateClientGrantResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*management.CreateClientGrantResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientGrantAPIV3MockRecorder) Create(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientGrantAPIV3)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockClientGrantAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientGrantAPIV3MockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientGrantAPIV3)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockClientGrantAPIV3) Get(ctx context.Context, id string, opts ...option.RequestOption) (*management.GetClientGrantResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetClientGrantResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientGrantAPIV3MockRecorder) Get(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientGrantAPIV3)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockClientGrantAPIV3) List(ctx context.Context, request *management.ListClientGrantsRequestParameters, opts ...option.RequestOption) (*auth0.ClientGrantPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.ClientGrantPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientGrantAPIV3MockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClientGrantAPIV3)(nil).List), varargs...)
}

// Update mocks base method.
func (m *MockClientGrantAPIV3) Update(ctx context.Context, id string, request *management.UpdateClientGrantRequestContent, opts ...option.RequestOption) (*management.UpdateClientGrantResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateClientGrantResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClientGrantAPIV3MockRecorder) Update(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClientGrantAPIV3)(nil).Update), varargs...)
}

// MockClientGrantOrganizationAPIV3 is a mock of ClientGrantOrganizationAPIV3 interface.
type MockClientGrantOrganizationAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockClientGrantOrganizationAPIV3MockRecorder
}

// MockClientGrantOrganizationAPIV3MockRecorder is the mock recorder for MockClientGrantOrganizationAPIV3.
type MockClientGrantOrganizationAPIV3MockRecorder struct {
	mock *MockClientGrantOrganizationAPIV3
}

// NewMockClientGrantOrganizationAPIV3 creates a new mock instance.
func NewMockClientGrantOrganizationAPIV3(ctrl *gomock.Controller) *MockClientGrantOrganizationAPIV3 {
	mock := &MockClientGrantOrganizationAPIV3{ctrl: ctrl}
	mock.recorder = &MockClientGrantOrganizationAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientGrantOrganizationAPIV3) EXPECT() *MockClientGrantOrganizationAPIV3MockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockClientGrantOrganizationAPIV3) List(ctx context.Context, id string, request *management.ListClientGrantOrganizationsRequestParameters, opts ...option.RequestOption) (*auth0.ClientGrantOrganizationPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.ClientGrantOrganizationPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientGrantOrganizationAPIV3MockRecorder) List(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClientGrantOrganizationAPIV3)(nil).List), varargs...)
}
