// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/management"
	gomock "github.com/golang/mock/gomock"
)

// MockClientGrantAPI is a mock of ClientAPI interface.
type MockClientGrantAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClientGrantAPIMockRecorder
}

// MockClientGrantAPIMockRecorder is the mock recorder for MockClientGrantAPI.
type MockClientGrantAPIMockRecorder struct {
	mock *MockClientGrantAPI
}

// NewMockClientGrantAPI creates a new mock instance.
func NewMockClientGrantAPI(ctrl *gomock.Controller) *MockClientGrantAPI {
	mock := &MockClientGrantAPI{ctrl: ctrl}
	mock.recorder = &MockClientGrantAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientGrantAPI) EXPECT() *MockClientGrantAPIMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockClientGrantAPI) List(ctx context.Context, opts ...management.RequestOption) (*management.ClientGrantList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*management.ClientGrantList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientGrantAPIMockRecorder) List(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClientGrantAPI)(nil).List), varargs...)
}
