// Code generated by MockGen. DO NOT EDIT.
// Source: connection_v3.go
//
// Generated by this command:
//
//	mockgen -source=connection_v3.go -destination=mock/connection_v3_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth0 "github.com/auth0/auth0-cli/internal/auth0"
	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionAPIV3 is a mock of ConnectionAPIV3 interface.
type MockConnectionAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionAPIV3MockRecorder
	isgomock struct{}
}

// MockConnectionAPIV3MockRecorder is the mock recorder for MockConnectionAPIV3.
type MockConnectionAPIV3MockRecorder struct {
	mock *MockConnectionAPIV3
}

// NewMockConnectionAPIV3 creates a new mock instance.
func NewMockConnectionAPIV3(ctrl *gomock.Controller) *MockConnectionAPIV3 {
	mock := &MockConnectionAPIV3{ctrl: ctrl}
	mock.recorder = &MockConnectionAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionAPIV3) EXPECT() *MockConnectionAPIV3MockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockConnectionAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConnectionAPIV3MockRecorder) Delete(ctx, id any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectionAPIV3)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockConnectionAPIV3) List(ctx context.Context, request *management.ListConnectionsQueryParameters, opts ...option.RequestOption) (*auth0.ConnectionForListPage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.ConnectionForListPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConnectionAPIV3MockRecorder) List(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConnectionAPIV3)(nil).List), varargs...)
}

// MockConnectionEnabledClientAPIV3 is a mock of ConnectionEnabledClientAPIV3 interface.
type MockConnectionEnabledClientAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionEnabledClientAPIV3MockRecorder
	isgomock struct{}
}

// MockConnectionEnabledClientAPIV3MockRecorder is the mock recorder for MockConnectionEnabledClientAPIV3.
type MockConnectionEnabledClientAPIV3MockRecorder struct {
	mock *MockConnectionEnabledClientAPIV3
}

// NewMockConnectionEnabledClientAPIV3 creates a new mock instance.
func NewMockConnectionEnabledClientAPIV3(ctrl *gomock.Controller) *MockConnectionEnabledClientAPIV3 {
	mock := &MockConnectionEnabledClientAPIV3{ctrl: ctrl}
	mock.recorder = &MockConnectionEnabledClientAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionEnabledClientAPIV3) EXPECT() *MockConnectionEnabledClientAPIV3MockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConnectionEnabledClientAPIV3) Get(ctx context.Context, id string, request *management.GetConnectionEnabledClientsRequestParameters, opts ...option.RequestOption) (*auth0.ConnectionEnabledClientPage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*auth0.ConnectionEnabledClientPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConnectionEnabledClientAPIV3MockRecorder) Get(ctx, id, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConnectionEnabledClientAPIV3)(nil).Get), varargs...)
}

// Update mocks base method.
func (m *MockConnectionEnabledClientAPIV3) Update(ctx context.Context, id string, request management.UpdateEnabledClientConnectionsRequestContent, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConnectionEnabledClientAPIV3MockRecorder) Update(ctx, id, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConnectionEnabledClientAPIV3)(nil).Update), varargs...)
}
