// Code generated by MockGen. DO NOT EDIT.
// Source: feature_flags.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v2/management"
	managementcore "github.com/auth0/go-auth0/v2/management/core"
	managementoption "github.com/auth0/go-auth0/v2/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockFeatureFlagsAPI is a mock of FeatureFlagsAPI interface.
type MockFeatureFlagsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagsAPIMockRecorder
}

// MockFeatureFlagsAPIMockRecorder is the mock recorder for MockFeatureFlagsAPI.
type MockFeatureFlagsAPIMockRecorder struct {
	mock *MockFeatureFlagsAPI
}

// NewMockFeatureFlagsAPI creates a new mock instance.
func NewMockFeatureFlagsAPI(ctrl *gomock.Controller) *MockFeatureFlagsAPI {
	mock := &MockFeatureFlagsAPI{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagsAPI) EXPECT() *MockFeatureFlagsAPIMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockFeatureFlagsAPI) List(ctx context.Context, request *management.ListFeatureFlagsRequestParameters, opts ...managementoption.RequestOption) (*managementcore.Page[*string, *management.FeatureFlag, *management.ListFeatureFlagsResponseContent], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*managementcore.Page[*string, *management.FeatureFlag, *management.ListFeatureFlagsResponseContent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeatureFlagsAPIMockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeatureFlagsAPI)(nil).List), varargs...)
}

// Create mocks base method.
func (m *MockFeatureFlagsAPI) Create(ctx context.Context, request *management.CreateFeatureFlagRequestContent, opts ...managementoption.RequestOption) (*management.CreateFeatureFlagResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*management.CreateFeatureFlagResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFeatureFlagsAPIMockRecorder) Create(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeatureFlagsAPI)(nil).Create), varargs...)
}

// Get mocks base method.
func (m *MockFeatureFlagsAPI) Get(ctx context.Context, id string, opts ...managementoption.RequestOption) (*management.GetFeatureFlagResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetFeatureFlagResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFeatureFlagsAPIMockRecorder) Get(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFeatureFlagsAPI)(nil).Get), varargs...)
}

// Update mocks base method.
func (m *MockFeatureFlagsAPI) Update(ctx context.Context, id string, request *management.UpdateFeatureFlagRequestContent, opts ...managementoption.RequestOption) (*management.UpdateFeatureFlagResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateFeatureFlagResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeatureFlagsAPIMockRecorder) Update(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeatureFlagsAPI)(nil).Update), varargs...)
}

// Delete mocks base method.
func (m *MockFeatureFlagsAPI) Delete(ctx context.Context, id string, opts ...managementoption.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeatureFlagsAPIMockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeatureFlagsAPI)(nil).Delete), varargs...)
}

// UpdateStatus mocks base method.
func (m *MockFeatureFlagsAPI) UpdateStatus(ctx context.Context, id string, request *management.UpdateFeatureFlagStatusRequestContent, opts ...managementoption.RequestOption) (*management.UpdateFeatureFlagStatusResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStatus", varargs...)
	ret0, _ := ret[0].(*management.UpdateFeatureFlagStatusResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFeatureFlagsAPIMockRecorder) UpdateStatus(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFeatureFlagsAPI)(nil).UpdateStatus), varargs...)
}

// MockVariationsAPI is a mock of VariationsAPI interface.
type MockVariationsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockVariationsAPIMockRecorder
}

// MockVariationsAPIMockRecorder is the mock recorder for MockVariationsAPI.
type MockVariationsAPIMockRecorder struct {
	mock *MockVariationsAPI
}

// NewMockVariationsAPI creates a new mock instance.
func NewMockVariationsAPI(ctrl *gomock.Controller) *MockVariationsAPI {
	mock := &MockVariationsAPI{ctrl: ctrl}
	mock.recorder = &MockVariationsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariationsAPI) EXPECT() *MockVariationsAPIMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockVariationsAPI) List(ctx context.Context, featureFlagID string, opts ...managementoption.RequestOption) (*management.ListVariationsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, featureFlagID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*management.ListVariationsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVariationsAPIMockRecorder) List(ctx, featureFlagID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, featureFlagID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVariationsAPI)(nil).List), varargs...)
}

// Create mocks base method.
func (m *MockVariationsAPI) Create(ctx context.Context, featureFlagID string, request *management.CreateVariationRequestContent, opts ...managementoption.RequestOption) (*management.CreateVariationResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, featureFlagID, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*management.CreateVariationResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVariationsAPIMockRecorder) Create(ctx, featureFlagID, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, featureFlagID, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVariationsAPI)(nil).Create), varargs...)
}

// Get mocks base method.
func (m *MockVariationsAPI) Get(ctx context.Context, featureFlagID string, variationID string, opts ...managementoption.RequestOption) (*management.GetVariationResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, featureFlagID, variationID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetVariationResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVariationsAPIMockRecorder) Get(ctx, featureFlagID, variationID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, featureFlagID, variationID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVariationsAPI)(nil).Get), varargs...)
}

// Update mocks base method.
func (m *MockVariationsAPI) Update(ctx context.Context, featureFlagID string, variationID string, request *management.UpdateVariationRequestContent, opts ...managementoption.RequestOption) (*management.UpdateVariationResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, featureFlagID, variationID, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateVariationResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVariationsAPIMockRecorder) Update(ctx, featureFlagID, variationID, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, featureFlagID, variationID, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVariationsAPI)(nil).Update), varargs...)
}

// Delete mocks base method.
func (m *MockVariationsAPI) Delete(ctx context.Context, featureFlagID string, variationID string, opts ...managementoption.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, featureFlagID, variationID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVariationsAPIMockRecorder) Delete(ctx, featureFlagID, variationID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, featureFlagID, variationID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVariationsAPI)(nil).Delete), varargs...)
}
