// Code generated by MockGen. DO NOT EDIT.
// Source: flow_v3.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth0 "github.com/auth0/auth0-cli/internal/auth0"
	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockFlowAPIV3 is a mock of FlowAPIV3 interface.
type MockFlowAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockFlowAPIV3MockRecorder
}

// MockFlowAPIV3MockRecorder is the mock recorder for MockFlowAPIV3.
type MockFlowAPIV3MockRecorder struct {
	mock *MockFlowAPIV3
}

// NewMockFlowAPIV3 creates a new mock instance.
func NewMockFlowAPIV3(ctrl *gomock.Controller) *MockFlowAPIV3 {
	mock := &MockFlowAPIV3{ctrl: ctrl}
	mock.recorder = &MockFlowAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowAPIV3) EXPECT() *MockFlowAPIV3MockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFlowAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlowAPIV3MockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlowAPIV3)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockFlowAPIV3) List(ctx context.Context, request *management.ListFlowsRequestParameters, opts ...option.RequestOption) (*auth0.FlowSummaryPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.FlowSummaryPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFlowAPIV3MockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFlowAPIV3)(nil).List), varargs...)
}

// MockFlowExecutionAPIV3 is a mock of FlowExecutionAPIV3 interface.
type MockFlowExecutionAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockFlowExecutionAPIV3MockRecorder
}

// MockFlowExecutionAPIV3MockRecorder is the mock recorder for MockFlowExecutionAPIV3.
type MockFlowExecutionAPIV3MockRecorder struct {
	mock *MockFlowExecutionAPIV3
}

// NewMockFlowExecutionAPIV3 creates a new mock instance.
func NewMockFlowExecutionAPIV3(ctrl *gomock.Controller) *MockFlowExecutionAPIV3 {
	mock := &MockFlowExecutionAPIV3{ctrl: ctrl}
	mock.recorder = &MockFlowExecutionAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowExecutionAPIV3) EXPECT() *MockFlowExecutionAPIV3MockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFlowExecutionAPIV3) Delete(ctx context.Context, flowID, executionID string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, flowID, executionID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlowExecutionAPIV3MockRecorder) Delete(ctx, flowID, executionID interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, flowID, executionID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlowExecutionAPIV3)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockFlowExecutionAPIV3) List(ctx context.Context, flowID string, request *management.ListFlowExecutionsRequestParameters, opts ...option.RequestOption) (*auth0.FlowExecutionSummaryPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, flowID, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.FlowExecutionSummaryPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFlowExecutionAPIV3MockRecorder) List(ctx, flowID, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, flowID, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFlowExecutionAPIV3)(nil).List), varargs...)
}

// MockFlowVaultConnectionAPIV3 is a mock of FlowVaultConnectionAPIV3 interface.
type MockFlowVaultConnectionAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockFlowVaultConnectionAPIV3MockRecorder
}

// MockFlowVaultConnectionAPIV3MockRecorder is the mock recorder for MockFlowVaultConnectionAPIV3.
type MockFlowVaultConnectionAPIV3MockRecorder struct {
	mock *MockFlowVaultConnectionAPIV3
}

// NewMockFlowVaultConnectionAPIV3 creates a new mock instance.
func NewMockFlowVaultConnectionAPIV3(ctrl *gomock.Controller) *MockFlowVaultConnectionAPIV3 {
	mock := &MockFlowVaultConnectionAPIV3{ctrl: ctrl}
	mock.recorder = &MockFlowVaultConnectionAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowVaultConnectionAPIV3) EXPECT() *MockFlowVaultConnectionAPIV3MockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFlowVaultConnectionAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlowVaultConnectionAPIV3MockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlowVaultConnectionAPIV3)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockFlowVaultConnectionAPIV3) List(ctx context.Context, request *management.ListFlowsVaultConnectionsRequestParameters, opts ...option.RequestOption) (*auth0.FlowsVaultConnectionSummaryPage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*auth0.FlowsVaultConnectionSummaryPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFlowVaultConnectionAPIV3MockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFlowVaultConnectionAPIV3)(nil).List), varargs...)
}
