// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_policy.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockGuardianPolicyAPIV3 is a mock of GuardianPolicyAPIV3 interface.
type MockGuardianPolicyAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianPolicyAPIV3MockRecorder
}

// MockGuardianPolicyAPIV3MockRecorder is the mock recorder for MockGuardianPolicyAPIV3.
type MockGuardianPolicyAPIV3MockRecorder struct {
	mock *MockGuardianPolicyAPIV3
}

// NewMockGuardianPolicyAPIV3 creates a new mock instance.
func NewMockGuardianPolicyAPIV3(ctrl *gomock.Controller) *MockGuardianPolicyAPIV3 {
	mock := &MockGuardianPolicyAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianPolicyAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianPolicyAPIV3) EXPECT() *MockGuardianPolicyAPIV3MockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGuardianPolicyAPIV3) List(ctx context.Context, opts ...option.RequestOption) (management.ListGuardianPoliciesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(management.ListGuardianPoliciesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGuardianPolicyAPIV3MockRecorder) List(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGuardianPolicyAPIV3)(nil).List), varargs...)
}

// Set mocks base method.
func (m *MockGuardianPolicyAPIV3) Set(ctx context.Context, request management.SetGuardianPoliciesRequestContent, opts ...option.RequestOption) (management.SetGuardianPoliciesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(management.SetGuardianPoliciesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockGuardianPolicyAPIV3MockRecorder) Set(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockGuardianPolicyAPIV3)(nil).Set), varargs...)
}
