// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_factor_sms.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockGuardianFactorSmsAPIV3 is a mock of GuardianFactorSmsAPIV3 interface.
type MockGuardianFactorSmsAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianFactorSmsAPIV3MockRecorder
}

// MockGuardianFactorSmsAPIV3MockRecorder is the mock recorder for MockGuardianFactorSmsAPIV3.
type MockGuardianFactorSmsAPIV3MockRecorder struct {
	mock *MockGuardianFactorSmsAPIV3
}

// NewMockGuardianFactorSmsAPIV3 creates a new mock instance.
func NewMockGuardianFactorSmsAPIV3(ctrl *gomock.Controller) *MockGuardianFactorSmsAPIV3 {
	mock := &MockGuardianFactorSmsAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianFactorSmsAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianFactorSmsAPIV3) EXPECT() *MockGuardianFactorSmsAPIV3MockRecorder {
	return m.recorder
}

// GetSelectedProvider mocks base method.
func (m *MockGuardianFactorSmsAPIV3) GetSelectedProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderSmsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSelectedProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderSmsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedProvider indicates an expected call of GetSelectedProvider.
func (mr *MockGuardianFactorSmsAPIV3MockRecorder) GetSelectedProvider(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedProvider", reflect.TypeOf((*MockGuardianFactorSmsAPIV3)(nil).GetSelectedProvider), varargs...)
}

// GetTemplates mocks base method.
func (m *MockGuardianFactorSmsAPIV3) GetTemplates(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorSmsTemplatesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTemplates", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorSmsTemplatesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockGuardianFactorSmsAPIV3MockRecorder) GetTemplates(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockGuardianFactorSmsAPIV3)(nil).GetTemplates), varargs...)
}

// GetTwilioProvider mocks base method.
func (m *MockGuardianFactorSmsAPIV3) GetTwilioProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderSmsTwilioResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTwilioProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderSmsTwilioResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwilioProvider indicates an expected call of GetTwilioProvider.
func (mr *MockGuardianFactorSmsAPIV3MockRecorder) GetTwilioProvider(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwilioProvider", reflect.TypeOf((*MockGuardianFactorSmsAPIV3)(nil).GetTwilioProvider), varargs...)
}

// SetProvider mocks base method.
func (m *MockGuardianFactorSmsAPIV3) SetProvider(ctx context.Context, request *management.SetGuardianFactorsProviderSmsRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderSmsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderSmsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProvider indicates an expected call of SetProvider.
func (mr *MockGuardianFactorSmsAPIV3MockRecorder) SetProvider(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvider", reflect.TypeOf((*MockGuardianFactorSmsAPIV3)(nil).SetProvider), varargs...)
}

// SetTemplates mocks base method.
func (m *MockGuardianFactorSmsAPIV3) SetTemplates(ctx context.Context, request *management.SetGuardianFactorSmsTemplatesRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorSmsTemplatesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTemplates", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorSmsTemplatesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTemplates indicates an expected call of SetTemplates.
func (mr *MockGuardianFactorSmsAPIV3MockRecorder) SetTemplates(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTemplates", reflect.TypeOf((*MockGuardianFactorSmsAPIV3)(nil).SetTemplates), varargs...)
}

// SetTwilioProvider mocks base method.
func (m *MockGuardianFactorSmsAPIV3) SetTwilioProvider(ctx context.Context, request *management.SetGuardianFactorsProviderSmsTwilioRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderSmsTwilioResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTwilioProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderSmsTwilioResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTwilioProvider indicates an expected call of SetTwilioProvider.
func (mr *MockGuardianFactorSmsAPIV3MockRecorder) SetTwilioProvider(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTwilioProvider", reflect.TypeOf((*MockGuardianFactorSmsAPIV3)(nil).SetTwilioProvider), varargs...)
}
