// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_factor_phone.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockGuardianFactorPhoneAPIV3 is a mock of GuardianFactorPhoneAPIV3 interface.
type MockGuardianFactorPhoneAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianFactorPhoneAPIV3MockRecorder
}

// MockGuardianFactorPhoneAPIV3MockRecorder is the mock recorder for MockGuardianFactorPhoneAPIV3.
type MockGuardianFactorPhoneAPIV3MockRecorder struct {
	mock *MockGuardianFactorPhoneAPIV3
}

// NewMockGuardianFactorPhoneAPIV3 creates a new mock instance.
func NewMockGuardianFactorPhoneAPIV3(ctrl *gomock.Controller) *MockGuardianFactorPhoneAPIV3 {
	mock := &MockGuardianFactorPhoneAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianFactorPhoneAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianFactorPhoneAPIV3) EXPECT() *MockGuardianFactorPhoneAPIV3MockRecorder {
	return m.recorder
}

// GetMessageTypes mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) GetMessageTypes(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorPhoneMessageTypesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMessageTypes", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorPhoneMessageTypesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageTypes indicates an expected call of GetMessageTypes.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) GetMessageTypes(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageTypes", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).GetMessageTypes), varargs...)
}

// GetSelectedProvider mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) GetSelectedProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderPhoneResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSelectedProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderPhoneResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedProvider indicates an expected call of GetSelectedProvider.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) GetSelectedProvider(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedProvider", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).GetSelectedProvider), varargs...)
}

// GetTemplates mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) GetTemplates(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorPhoneTemplatesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTemplates", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorPhoneTemplatesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) GetTemplates(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).GetTemplates), varargs...)
}

// GetTwilioProvider mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) GetTwilioProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderPhoneTwilioResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTwilioProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderPhoneTwilioResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwilioProvider indicates an expected call of GetTwilioProvider.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) GetTwilioProvider(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwilioProvider", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).GetTwilioProvider), varargs...)
}

// SetMessageTypes mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) SetMessageTypes(ctx context.Context, request *management.SetGuardianFactorPhoneMessageTypesRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorPhoneMessageTypesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMessageTypes", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorPhoneMessageTypesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMessageTypes indicates an expected call of SetMessageTypes.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) SetMessageTypes(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessageTypes", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).SetMessageTypes), varargs...)
}

// SetProvider mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) SetProvider(ctx context.Context, request *management.SetGuardianFactorsProviderPhoneRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderPhoneResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderPhoneResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProvider indicates an expected call of SetProvider.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) SetProvider(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvider", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).SetProvider), varargs...)
}

// SetTemplates mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) SetTemplates(ctx context.Context, request *management.SetGuardianFactorPhoneTemplatesRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorPhoneTemplatesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTemplates", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorPhoneTemplatesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTemplates indicates an expected call of SetTemplates.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) SetTemplates(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTemplates", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).SetTemplates), varargs...)
}

// SetTwilioProvider mocks base method.
func (m *MockGuardianFactorPhoneAPIV3) SetTwilioProvider(ctx context.Context, request *management.SetGuardianFactorsProviderPhoneTwilioRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderPhoneTwilioResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTwilioProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderPhoneTwilioResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTwilioProvider indicates an expected call of SetTwilioProvider.
func (mr *MockGuardianFactorPhoneAPIV3MockRecorder) SetTwilioProvider(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTwilioProvider", reflect.TypeOf((*MockGuardianFactorPhoneAPIV3)(nil).SetTwilioProvider), varargs...)
}
