// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_factor_push.go
//
// Generated by this command:
//
//	mockgen -source=guardian_factor_push.go -destination=mock/guardian_factor_push_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "go.uber.org/mock/gomock"
)

// MockGuardianFactorPushAPIV3 is a mock of GuardianFactorPushAPIV3 interface.
type MockGuardianFactorPushAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianFactorPushAPIV3MockRecorder
	isgomock struct{}
}

// MockGuardianFactorPushAPIV3MockRecorder is the mock recorder for MockGuardianFactorPushAPIV3.
type MockGuardianFactorPushAPIV3MockRecorder struct {
	mock *MockGuardianFactorPushAPIV3
}

// NewMockGuardianFactorPushAPIV3 creates a new mock instance.
func NewMockGuardianFactorPushAPIV3(ctrl *gomock.Controller) *MockGuardianFactorPushAPIV3 {
	mock := &MockGuardianFactorPushAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianFactorPushAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianFactorPushAPIV3) EXPECT() *MockGuardianFactorPushAPIV3MockRecorder {
	return m.recorder
}

// GetApnsProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) GetApnsProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderApnsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApnsProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderApnsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApnsProvider indicates an expected call of GetApnsProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) GetApnsProvider(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApnsProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).GetApnsProvider), varargs...)
}

// GetSelectedProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) GetSelectedProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderPushNotificationResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSelectedProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderPushNotificationResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedProvider indicates an expected call of GetSelectedProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) GetSelectedProvider(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).GetSelectedProvider), varargs...)
}

// GetSnsProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) GetSnsProvider(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorsProviderSnsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSnsProvider", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorsProviderSnsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnsProvider indicates an expected call of GetSnsProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) GetSnsProvider(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnsProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).GetSnsProvider), varargs...)
}

// SetApnsProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) SetApnsProvider(ctx context.Context, request *management.SetGuardianFactorsProviderPushNotificationApnsRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderPushNotificationApnsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetApnsProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderPushNotificationApnsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetApnsProvider indicates an expected call of SetApnsProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) SetApnsProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApnsProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).SetApnsProvider), varargs...)
}

// SetFcmProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) SetFcmProvider(ctx context.Context, request *management.SetGuardianFactorsProviderPushNotificationFcmRequestContent, opts ...option.RequestOption) (management.SetGuardianFactorsProviderPushNotificationFcmResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetFcmProvider", varargs...)
	ret0, _ := ret[0].(management.SetGuardianFactorsProviderPushNotificationFcmResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFcmProvider indicates an expected call of SetFcmProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) SetFcmProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFcmProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).SetFcmProvider), varargs...)
}

// SetFcmv1Provider mocks base method.
func (m *MockGuardianFactorPushAPIV3) SetFcmv1Provider(ctx context.Context, request *management.SetGuardianFactorsProviderPushNotificationFcmv1RequestContent, opts ...option.RequestOption) (management.SetGuardianFactorsProviderPushNotificationFcmv1ResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetFcmv1Provider", varargs...)
	ret0, _ := ret[0].(management.SetGuardianFactorsProviderPushNotificationFcmv1ResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFcmv1Provider indicates an expected call of SetFcmv1Provider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) SetFcmv1Provider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFcmv1Provider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).SetFcmv1Provider), varargs...)
}

// SetProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) SetProvider(ctx context.Context, request *management.SetGuardianFactorsProviderPushNotificationRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderPushNotificationResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderPushNotificationResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProvider indicates an expected call of SetProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) SetProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).SetProvider), varargs...)
}

// SetSnsProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) SetSnsProvider(ctx context.Context, request *management.SetGuardianFactorsProviderPushNotificationSnsRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorsProviderPushNotificationSnsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetSnsProvider", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorsProviderPushNotificationSnsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSnsProvider indicates an expected call of SetSnsProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) SetSnsProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSnsProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).SetSnsProvider), varargs...)
}

// UpdateApnsProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) UpdateApnsProvider(ctx context.Context, request *management.UpdateGuardianFactorsProviderPushNotificationApnsRequestContent, opts ...option.RequestOption) (*management.UpdateGuardianFactorsProviderPushNotificationApnsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateApnsProvider", varargs...)
	ret0, _ := ret[0].(*management.UpdateGuardianFactorsProviderPushNotificationApnsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateApnsProvider indicates an expected call of UpdateApnsProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) UpdateApnsProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApnsProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).UpdateApnsProvider), varargs...)
}

// UpdateFcmProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) UpdateFcmProvider(ctx context.Context, request *management.UpdateGuardianFactorsProviderPushNotificationFcmRequestContent, opts ...option.RequestOption) (management.UpdateGuardianFactorsProviderPushNotificationFcmResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateFcmProvider", varargs...)
	ret0, _ := ret[0].(management.UpdateGuardianFactorsProviderPushNotificationFcmResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFcmProvider indicates an expected call of UpdateFcmProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) UpdateFcmProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFcmProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).UpdateFcmProvider), varargs...)
}

// UpdateFcmv1Provider mocks base method.
func (m *MockGuardianFactorPushAPIV3) UpdateFcmv1Provider(ctx context.Context, request *management.UpdateGuardianFactorsProviderPushNotificationFcmv1RequestContent, opts ...option.RequestOption) (management.UpdateGuardianFactorsProviderPushNotificationFcmv1ResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateFcmv1Provider", varargs...)
	ret0, _ := ret[0].(management.UpdateGuardianFactorsProviderPushNotificationFcmv1ResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFcmv1Provider indicates an expected call of UpdateFcmv1Provider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) UpdateFcmv1Provider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFcmv1Provider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).UpdateFcmv1Provider), varargs...)
}

// UpdateSnsProvider mocks base method.
func (m *MockGuardianFactorPushAPIV3) UpdateSnsProvider(ctx context.Context, request *management.UpdateGuardianFactorsProviderPushNotificationSnsRequestContent, opts ...option.RequestOption) (*management.UpdateGuardianFactorsProviderPushNotificationSnsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSnsProvider", varargs...)
	ret0, _ := ret[0].(*management.UpdateGuardianFactorsProviderPushNotificationSnsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSnsProvider indicates an expected call of UpdateSnsProvider.
func (mr *MockGuardianFactorPushAPIV3MockRecorder) UpdateSnsProvider(ctx, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSnsProvider", reflect.TypeOf((*MockGuardianFactorPushAPIV3)(nil).UpdateSnsProvider), varargs...)
}
