// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_enrollment.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockGuardianEnrollmentAPIV3 is a mock of GuardianEnrollmentAPIV3 interface.
type MockGuardianEnrollmentAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianEnrollmentAPIV3MockRecorder
}

// MockGuardianEnrollmentAPIV3MockRecorder is the mock recorder for MockGuardianEnrollmentAPIV3.
type MockGuardianEnrollmentAPIV3MockRecorder struct {
	mock *MockGuardianEnrollmentAPIV3
}

// NewMockGuardianEnrollmentAPIV3 creates a new mock instance.
func NewMockGuardianEnrollmentAPIV3(ctrl *gomock.Controller) *MockGuardianEnrollmentAPIV3 {
	mock := &MockGuardianEnrollmentAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianEnrollmentAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianEnrollmentAPIV3) EXPECT() *MockGuardianEnrollmentAPIV3MockRecorder {
	return m.recorder
}

// CreateTicket mocks base method.
func (m *MockGuardianEnrollmentAPIV3) CreateTicket(ctx context.Context, request *management.CreateGuardianEnrollmentTicketRequestContent, opts ...option.RequestOption) (*management.CreateGuardianEnrollmentTicketResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTicket", varargs...)
	ret0, _ := ret[0].(*management.CreateGuardianEnrollmentTicketResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockGuardianEnrollmentAPIV3MockRecorder) CreateTicket(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockGuardianEnrollmentAPIV3)(nil).CreateTicket), varargs...)
}

// Delete mocks base method.
func (m *MockGuardianEnrollmentAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGuardianEnrollmentAPIV3MockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGuardianEnrollmentAPIV3)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockGuardianEnrollmentAPIV3) Get(ctx context.Context, id string, opts ...option.RequestOption) (*management.GetGuardianEnrollmentResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianEnrollmentResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGuardianEnrollmentAPIV3MockRecorder) Get(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGuardianEnrollmentAPIV3)(nil).Get), varargs...)
}
