// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_factor.go
//
// Generated by this command:
//
//	mockgen -source=guardian_factor.go -destination=mock/guardian_factor_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "go.uber.org/mock/gomock"
)

// MockGuardianFactorAPIV3 is a mock of GuardianFactorAPIV3 interface.
type MockGuardianFactorAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianFactorAPIV3MockRecorder
	isgomock struct{}
}

// MockGuardianFactorAPIV3MockRecorder is the mock recorder for MockGuardianFactorAPIV3.
type MockGuardianFactorAPIV3MockRecorder struct {
	mock *MockGuardianFactorAPIV3
}

// NewMockGuardianFactorAPIV3 creates a new mock instance.
func NewMockGuardianFactorAPIV3(ctrl *gomock.Controller) *MockGuardianFactorAPIV3 {
	mock := &MockGuardianFactorAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianFactorAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianFactorAPIV3) EXPECT() *MockGuardianFactorAPIV3MockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGuardianFactorAPIV3) List(ctx context.Context, opts ...option.RequestOption) ([]*management.GuardianFactor, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*management.GuardianFactor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGuardianFactorAPIV3MockRecorder) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGuardianFactorAPIV3)(nil).List), varargs...)
}

// Set mocks base method.
func (m *MockGuardianFactorAPIV3) Set(ctx context.Context, name *management.GuardianFactorNameEnum, request *management.SetGuardianFactorRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockGuardianFactorAPIV3MockRecorder) Set(ctx, name, request any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockGuardianFactorAPIV3)(nil).Set), varargs...)
}
