// Code generated by MockGen. DO NOT EDIT.
// Source: guardian_factor_duo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockGuardianFactorDuoAPIV3 is a mock of GuardianFactorDuoAPIV3 interface.
type MockGuardianFactorDuoAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockGuardianFactorDuoAPIV3MockRecorder
}

// MockGuardianFactorDuoAPIV3MockRecorder is the mock recorder for MockGuardianFactorDuoAPIV3.
type MockGuardianFactorDuoAPIV3MockRecorder struct {
	mock *MockGuardianFactorDuoAPIV3
}

// NewMockGuardianFactorDuoAPIV3 creates a new mock instance.
func NewMockGuardianFactorDuoAPIV3(ctrl *gomock.Controller) *MockGuardianFactorDuoAPIV3 {
	mock := &MockGuardianFactorDuoAPIV3{ctrl: ctrl}
	mock.recorder = &MockGuardianFactorDuoAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuardianFactorDuoAPIV3) EXPECT() *MockGuardianFactorDuoAPIV3MockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGuardianFactorDuoAPIV3) Get(ctx context.Context, opts ...option.RequestOption) (*management.GetGuardianFactorDuoSettingsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetGuardianFactorDuoSettingsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGuardianFactorDuoAPIV3MockRecorder) Get(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGuardianFactorDuoAPIV3)(nil).Get), varargs...)
}

// Set mocks base method.
func (m *MockGuardianFactorDuoAPIV3) Set(ctx context.Context, request *management.SetGuardianFactorDuoSettingsRequestContent, opts ...option.RequestOption) (*management.SetGuardianFactorDuoSettingsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(*management.SetGuardianFactorDuoSettingsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockGuardianFactorDuoAPIV3MockRecorder) Set(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockGuardianFactorDuoAPIV3)(nil).Set), varargs...)
}

// Update mocks base method.
func (m *MockGuardianFactorDuoAPIV3) Update(ctx context.Context, request *management.UpdateGuardianFactorDuoSettingsRequestContent, opts ...option.RequestOption) (*management.UpdateGuardianFactorDuoSettingsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateGuardianFactorDuoSettingsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGuardianFactorDuoAPIV3MockRecorder) Update(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGuardianFactorDuoAPIV3)(nil).Update), varargs...)
}
