// Code generated by MockGen. DO NOT EDIT.
// Source: log_stream.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	management "github.com/auth0/go-auth0/management"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLogStreamAPI is a mock of LogStreamAPI interface
type MockLogStreamAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLogStreamAPIMockRecorder
}

// MockLogStreamAPIMockRecorder is the mock recorder for MockLogStreamAPI
type MockLogStreamAPIMockRecorder struct {
	mock *MockLogStreamAPI
}

// NewMockLogStreamAPI creates a new mock instance
func NewMockLogStreamAPI(ctrl *gomock.Controller) *MockLogStreamAPI {
	mock := &MockLogStreamAPI{ctrl: ctrl}
	mock.recorder = &MockLogStreamAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogStreamAPI) EXPECT() *MockLogStreamAPIMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockLogStreamAPI) Create(ctx context.Context, ls *management.LogStream, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, ls}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockLogStreamAPIMockRecorder) Create(ctx, ls interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, ls}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLogStreamAPI)(nil).Create), varargs...)
}

// Read mocks base method
func (m *MockLogStreamAPI) Read(ctx context.Context, id string, opts ...management.RequestOption) (*management.LogStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(*management.LogStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockLogStreamAPIMockRecorder) Read(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockLogStreamAPI)(nil).Read), varargs...)
}

// Update mocks base method
func (m *MockLogStreamAPI) Update(ctx context.Context, id string, ls *management.LogStream, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, ls}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockLogStreamAPIMockRecorder) Update(ctx, id, ls interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, ls}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLogStreamAPI)(nil).Update), varargs...)
}

// List mocks base method
func (m *MockLogStreamAPI) List(ctx context.Context, opts ...management.RequestOption) ([]*management.LogStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*management.LogStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockLogStreamAPIMockRecorder) List(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLogStreamAPI)(nil).List), varargs...)
}

// Delete mocks base method
func (m *MockLogStreamAPI) Delete(ctx context.Context, id string, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockLogStreamAPIMockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLogStreamAPI)(nil).Delete), varargs...)
}
