// Code generated by MockGen. DO NOT EDIT.
// Source: network_acl.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/management"
	gomock "github.com/golang/mock/gomock"
)

// MockNetworkACLAPI is a mock of NetworkACLAPI interface.
type MockNetworkACLAPI struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkACLAPIMockRecorder
}

// MockNetworkACLAPIMockRecorder is the mock recorder for MockNetworkACLAPI.
type MockNetworkACLAPIMockRecorder struct {
	mock *MockNetworkACLAPI
}

// NewMockNetworkACLAPI creates a new mock instance.
func NewMockNetworkACLAPI(ctrl *gomock.Controller) *MockNetworkACLAPI {
	mock := &MockNetworkACLAPI{ctrl: ctrl}
	mock.recorder = &MockNetworkACLAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkACLAPI) EXPECT() *MockNetworkACLAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetworkACLAPI) Create(ctx context.Context, n *management.NetworkACL, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, n}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNetworkACLAPIMockRecorder) Create(ctx, n interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, n}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetworkACLAPI)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockNetworkACLAPI) Delete(ctx context.Context, id string, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNetworkACLAPIMockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNetworkACLAPI)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockNetworkACLAPI) List(ctx context.Context, opts ...management.RequestOption) ([]*management.NetworkACL, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*management.NetworkACL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNetworkACLAPIMockRecorder) List(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNetworkACLAPI)(nil).List), varargs...)
}

// Read mocks base method.
func (m *MockNetworkACLAPI) Read(ctx context.Context, id string, opts ...management.RequestOption) (*management.NetworkACL, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(*management.NetworkACL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockNetworkACLAPIMockRecorder) Read(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockNetworkACLAPI)(nil).Read), varargs...)
}

// Update mocks base method.
func (m *MockNetworkACLAPI) Update(ctx context.Context, id string, n *management.NetworkACL, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, n}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNetworkACLAPIMockRecorder) Update(ctx, id, n interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, n}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNetworkACLAPI)(nil).Update), varargs...)
}
