// Code generated by MockGen. DO NOT EDIT.
// Source: network_acl_key.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockNetworkACLKeyAPIV3 is a mock of NetworkACLKeyAPIV3 interface.
type MockNetworkACLKeyAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkACLKeyAPIV3MockRecorder
}

// MockNetworkACLKeyAPIV3MockRecorder is the mock recorder for MockNetworkACLKeyAPIV3.
type MockNetworkACLKeyAPIV3MockRecorder struct {
	mock *MockNetworkACLKeyAPIV3
}

// NewMockNetworkACLKeyAPIV3 creates a new mock instance.
func NewMockNetworkACLKeyAPIV3(ctrl *gomock.Controller) *MockNetworkACLKeyAPIV3 {
	mock := &MockNetworkACLKeyAPIV3{ctrl: ctrl}
	mock.recorder = &MockNetworkACLKeyAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkACLKeyAPIV3) EXPECT() *MockNetworkACLKeyAPIV3MockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockNetworkACLKeyAPIV3) List(ctx context.Context, opts ...option.RequestOption) (*management.GetAllKeysNetworkACLsResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*management.GetAllKeysNetworkACLsResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNetworkACLKeyAPIV3MockRecorder) List(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNetworkACLKeyAPIV3)(nil).List), varargs...)
}
