// Code generated by MockGen. DO NOT EDIT.
// Source: phone_notification_template.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v2/management"
	option "github.com/auth0/go-auth0/v2/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockPhoneNotificationTemplateAPI is a mock of PhoneNotificationTemplateAPI interface.
type MockPhoneNotificationTemplateAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPhoneNotificationTemplateAPIMockRecorder
}

// MockPhoneNotificationTemplateAPIMockRecorder is the mock recorder for MockPhoneNotificationTemplateAPI.
type MockPhoneNotificationTemplateAPIMockRecorder struct {
	mock *MockPhoneNotificationTemplateAPI
}

// NewMockPhoneNotificationTemplateAPI creates a new mock instance.
func NewMockPhoneNotificationTemplateAPI(ctrl *gomock.Controller) *MockPhoneNotificationTemplateAPI {
	mock := &MockPhoneNotificationTemplateAPI{ctrl: ctrl}
	mock.recorder = &MockPhoneNotificationTemplateAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhoneNotificationTemplateAPI) EXPECT() *MockPhoneNotificationTemplateAPIMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPhoneNotificationTemplateAPI) List(ctx context.Context, request *management.ListPhoneTemplatesRequestParameters, opts ...option.RequestOption) (*management.ListPhoneTemplatesResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*management.ListPhoneTemplatesResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPhoneNotificationTemplateAPIMockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPhoneNotificationTemplateAPI)(nil).List), varargs...)
}
