// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_token.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v3/management"
	option "github.com/auth0/go-auth0/v3/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockRefreshTokenAPIV3 is a mock of RefreshTokenAPIV3 interface.
type MockRefreshTokenAPIV3 struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenAPIV3MockRecorder
}

// MockRefreshTokenAPIV3MockRecorder is the mock recorder for MockRefreshTokenAPIV3.
type MockRefreshTokenAPIV3MockRecorder struct {
	mock *MockRefreshTokenAPIV3
}

// NewMockRefreshTokenAPIV3 creates a new mock instance.
func NewMockRefreshTokenAPIV3(ctrl *gomock.Controller) *MockRefreshTokenAPIV3 {
	mock := &MockRefreshTokenAPIV3{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenAPIV3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenAPIV3) EXPECT() *MockRefreshTokenAPIV3MockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRefreshTokenAPIV3) Delete(ctx context.Context, id string, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenAPIV3MockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenAPIV3)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockRefreshTokenAPIV3) Get(ctx context.Context, id string, opts ...option.RequestOption) (*management.GetRefreshTokenResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetRefreshTokenResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRefreshTokenAPIV3MockRecorder) Get(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRefreshTokenAPIV3)(nil).Get), varargs...)
}

// Revoke mocks base method.
func (m *MockRefreshTokenAPIV3) Revoke(ctx context.Context, request *management.RevokeRefreshTokensRequestContent, opts ...option.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Revoke", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenAPIV3MockRecorder) Revoke(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenAPIV3)(nil).Revoke), varargs...)
}

// Update mocks base method.
func (m *MockRefreshTokenAPIV3) Update(ctx context.Context, id string, request *management.UpdateRefreshTokenRequestContent, opts ...option.RequestOption) (*management.UpdateRefreshTokenResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateRefreshTokenResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRefreshTokenAPIV3MockRecorder) Update(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefreshTokenAPIV3)(nil).Update), varargs...)
}
