// Code generated by MockGen. DO NOT EDIT.
// Source: segments.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/v2/management"
	managementcore "github.com/auth0/go-auth0/v2/management/core"
	managementoption "github.com/auth0/go-auth0/v2/management/option"
	gomock "github.com/golang/mock/gomock"
)

// MockSegmentsAPI is a mock of SegmentsAPI interface.
type MockSegmentsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentsAPIMockRecorder
}

// MockSegmentsAPIMockRecorder is the mock recorder for MockSegmentsAPI.
type MockSegmentsAPIMockRecorder struct {
	mock *MockSegmentsAPI
}

// NewMockSegmentsAPI creates a new mock instance.
func NewMockSegmentsAPI(ctrl *gomock.Controller) *MockSegmentsAPI {
	mock := &MockSegmentsAPI{ctrl: ctrl}
	mock.recorder = &MockSegmentsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentsAPI) EXPECT() *MockSegmentsAPIMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSegmentsAPI) List(ctx context.Context, request *management.ListSegmentsRequestParameters, opts ...managementoption.RequestOption) (*managementcore.Page[*string, *management.Segment, *management.ListSegmentsResponseContent], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*managementcore.Page[*string, *management.Segment, *management.ListSegmentsResponseContent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSegmentsAPIMockRecorder) List(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSegmentsAPI)(nil).List), varargs...)
}

// Create mocks base method.
func (m *MockSegmentsAPI) Create(ctx context.Context, request *management.CreateSegmentRequestContent, opts ...managementoption.RequestOption) (*management.CreateSegmentResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*management.CreateSegmentResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSegmentsAPIMockRecorder) Create(ctx, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSegmentsAPI)(nil).Create), varargs...)
}

// Get mocks base method.
func (m *MockSegmentsAPI) Get(ctx context.Context, id string, opts ...managementoption.RequestOption) (*management.GetSegmentResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*management.GetSegmentResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSegmentsAPIMockRecorder) Get(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSegmentsAPI)(nil).Get), varargs...)
}

// Update mocks base method.
func (m *MockSegmentsAPI) Update(ctx context.Context, id string, request *management.UpdateSegmentRequestContent, opts ...managementoption.RequestOption) (*management.UpdateSegmentResponseContent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*management.UpdateSegmentResponseContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSegmentsAPIMockRecorder) Update(ctx, id, request interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, request}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSegmentsAPI)(nil).Update), varargs...)
}

// Delete mocks base method.
func (m *MockSegmentsAPI) Delete(ctx context.Context, id string, opts ...managementoption.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSegmentsAPIMockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSegmentsAPI)(nil).Delete), varargs...)
}
