// Code generated by MockGen. DO NOT EDIT.
// Source: token_exchange.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	management "github.com/auth0/go-auth0/management"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenExchangeAPI is a mock of TokenExchangeAPI interface.
type MockTokenExchangeAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTokenExchangeAPIMockRecorder
}

// MockTokenExchangeAPIMockRecorder is the mock recorder for MockTokenExchangeAPI.
type MockTokenExchangeAPIMockRecorder struct {
	mock *MockTokenExchangeAPI
}

// NewMockTokenExchangeAPI creates a new mock instance.
func NewMockTokenExchangeAPI(ctrl *gomock.Controller) *MockTokenExchangeAPI {
	mock := &MockTokenExchangeAPI{ctrl: ctrl}
	mock.recorder = &MockTokenExchangeAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenExchangeAPI) EXPECT() *MockTokenExchangeAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTokenExchangeAPI) Create(ctx context.Context, profile *management.TokenExchangeProfile, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, profile}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTokenExchangeAPIMockRecorder) Create(ctx, profile interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, profile}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTokenExchangeAPI)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockTokenExchangeAPI) Delete(ctx context.Context, id string, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTokenExchangeAPIMockRecorder) Delete(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTokenExchangeAPI)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockTokenExchangeAPI) List(ctx context.Context, opts ...management.RequestOption) (*management.TokenExchangeProfileList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*management.TokenExchangeProfileList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTokenExchangeAPIMockRecorder) List(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTokenExchangeAPI)(nil).List), varargs...)
}

// Read mocks base method.
func (m *MockTokenExchangeAPI) Read(ctx context.Context, id string, opts ...management.RequestOption) (*management.TokenExchangeProfile, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(*management.TokenExchangeProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockTokenExchangeAPIMockRecorder) Read(ctx, id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockTokenExchangeAPI)(nil).Read), varargs...)
}

// Update mocks base method.
func (m *MockTokenExchangeAPI) Update(ctx context.Context, id string, profile *management.TokenExchangeProfile, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, profile}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTokenExchangeAPIMockRecorder) Update(ctx, id, profile interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, profile}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTokenExchangeAPI)(nil).Update), varargs...)
}
