version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - godot
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    godot:
      scope: all
      capital: true
      period: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: package comment should be of the form
      - path: (.+)\.go$
        text: should have comment
      - path: (.+)\.go$
        text: be unexported
      - path: (.+)\.go$
        text: blank-imports
      - path: (.+)\.go$
        text: unused-parameter
      - path: (.+)\.go$
        text: Error return value of (.+) is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/auth0/auth0-cli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
