# Documentation at http://goreleaser.com
builds:
  - main: ./cmd/auth0
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    binary: auth0
    ldflags:
      - -X 'github.com/auth0/auth0-cli/internal/buildinfo.Version={{.Version}}'
      - -X 'github.com/auth0/auth0-cli/internal/buildinfo.Revision={{.Commit}}'
      - -X 'github.com/auth0/auth0-cli/internal/buildinfo.BuildUser=goreleaser'
      - -X 'github.com/auth0/auth0-cli/internal/buildinfo.BuildDate={{.Date}}'
      - -X 'github.com/auth0/auth0-cli/internal/instrumentation.SentryDSN={{.Env.SENTRY_DSN}}'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "arm64" }}arm64{{ else }}x86_64{{ end }}'
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  skip: true
brews:
  - name: auth0
    repository:
      owner: auth0
      name: homebrew-auth0-cli
    commit_author:
      name: auth0
      email: support@auth0.com
    homepage: https://auth0.github.io/auth0-cli
    description: Build, manage and test your Auth0 integrations from the command line
    license: MIT
    skip_upload: auto
    install: |
      bin.install "auth0"

      (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
      (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
      (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
    caveats: "Thanks for installing the Auth0 CLI"
scoops:
  - name: auth0
    repository:
      owner: auth0
      name: scoop-auth0-cli
    commit_author:
      name: auth0
      email: support@auth0.com
    commit_msg_template: "Scoop manifest update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://auth0.github.io/auth0-cli
    description: Build, manage and test your Auth0 integrations from the command line
    license: MIT
    skip_upload: auto
    post_install: ["Write-Host 'Thanks for installing the Auth0 CLI'"]
