blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://community.auth0.com/c/sdks/5
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: 📖 Auth0 CLI Documentation
    url: https://auth0.github.io/auth0-cli/
    about: Check the Auth0 CLI documentation for in-depth overview of all the available commands
