package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// DetectionResult holds the values resolved by scanning the working directory.
// Fields are empty/zero when not detected. AmbiguousCandidates is populated when
// multiple package.json deps match and the framework cannot be determined uniquely.
type DetectionResult struct {
	Framework           string
	Type                string   // "spa" | "regular" | "native".
	BuildTool           string   // "vite" | "maven" | "gradle" | "composer" | "" (NA).
	Port                int      // 0 means no applicable default.
	AppName             string   // Basename of the working directory.
	BundleID            string   // Package/bundle ID for native apps (e.g. "com.example.myapp"); empty if not found.
	Detected            bool     // True if any signal file matched.
	AmbiguousCandidates []string // Set when >1 package.json dep matched.
}

// detectionCandidate is used internally during package.json dep scanning.
type detectionCandidate struct {
	framework string
	qsType    string
	buildTool string
	port      int
}

// DetectProject scans dir for framework signal files and returns a DetectionResult.
// Rules follow the priority order from the spec: config files beat package.json scanning.
func DetectProject(dir string) DetectionResult {
	result := DetectionResult{
		AppName: filepath.Base(dir),
	}
	if name := readProjectName(dir); name != "" {
		result.AppName = name
	}

	// Read package.json deps early — needed for checks that must precede file-based signals.
	earlyDeps := readPackageJSONDeps(dir)

	// ── 1. Manage.py — must check BEFORE Ionic to prevent monorepo misdetection ──.
	// Manage.py is universally generated by django-admin startproject and is unique
	// to Django — no other Python framework produces it. Checking it before Ionic
	// ensures a Django+Ionic monorepo is detected as Django rather than Ionic.
	if fileExists(dir, "manage.py") {
		result.Framework = "django"
		result.Type = "regular"
		result.Port = 8000
		result.Detected = true
		return result
	}

	// ── 2. Ionic (package.json deps — must check BEFORE angular.json and vite.config) ──.
	if hasDep(earlyDeps, "@ionic/angular") {
		result.Framework = "ionic-angular"
		result.Type = "native"
		result.BundleID = readCapacitorAppID(dir)
		result.Detected = true
		return result
	}
	if hasDep(earlyDeps, "@ionic/react") {
		result.Framework = "ionic-react"
		result.Type = "native"
		result.BuildTool = detectBuildToolFromFiles(dir, "ionic-react")
		result.BundleID = readCapacitorAppID(dir)
		result.Detected = true
		return result
	}
	if hasDep(earlyDeps, "@ionic/vue") {
		result.Framework = "ionic-vue"
		result.Type = "native"
		result.BuildTool = detectBuildToolFromFiles(dir, "ionic-vue")
		result.BundleID = readCapacitorAppID(dir)
		result.Detected = true
		return result
	}

	// ── 3. Angular.json ────────────────────────────────────────────────────.
	if fileExists(dir, "angular.json") {
		result.Framework = "angular"
		result.Type = "spa"
		result.Port = detectPortFromConfig(dir, "angular", 4200)
		result.Detected = true
		return result
	}

	// ── 4. Pubspec.yaml (Flutter) ───────────────────────────────────────────.
	if data, ok := readFileContent(dir, "pubspec.yaml"); ok {
		if strings.Contains(data, "sdk: flutter") {
			result.Detected = true
			// Flutter create (default) has included web/ since Flutter 2.10, so web/ alone
			// is not a reliable signal for web-only intent.
			if dirExists(dir, "android") || dirExists(dir, "ios") {
				result.Framework = "flutter"
				result.Type = "native"
				result.BundleID = readMobileBundleID(dir)
			} else {
				result.Framework = "flutter-web"
				result.Type = "spa"
			}
			return result
		}
	}

	// ── 5. Composer.json (PHP) — BEFORE vite.config to prevent Laravel misdetection ──.
	// Laravel 10+ ships with vite.config.js; checking composer.json first avoids a
	// false-positive Vanilla-JavaScript match for Laravel projects.
	if data, ok := readFileContent(dir, "composer.json"); ok {
		result.BuildTool = "composer"
		result.Type = "regular"
		result.Detected = true
		if strings.Contains(data, "laravel/framework") {
			result.Framework = "laravel"
			result.Port = 8000
		} else {
			result.Framework = "vanilla-php"
		}
		return result
	}

	// ── 6. SvelteKit (@sveltejs/kit dep — BEFORE vite.config) ───────────────.
	// Plain Svelte+Vite also creates svelte.config.js and vite.config.ts, so
	// @sveltejs/kit in package.json is the only reliable distinguishing signal.
	if hasDep(earlyDeps, "@sveltejs/kit") {
		result.Framework = "sveltekit"
		result.Type = "regular"
		result.BuildTool = detectBuildToolFromFiles(dir, "sveltekit")
		result.Port = detectPortFromConfig(dir, "sveltekit", 3000)
		result.Detected = true
		return result
	}

	// ── 7. Nuxt.config.[ts|js] — BEFORE vite.config ─────────────────────────.
	// Nuxt uses Vite internally, so Nuxt projects commonly contain vite.config.ts
	// alongside nuxt.config.ts. Checking nuxt.config first prevents a Nuxt project
	// from being misdetected as a Vite SPA.
	if fileExistsAny(dir, "nuxt.config.ts", "nuxt.config.js") {
		result.Framework = "nuxt"
		result.Type = "regular"
		result.Port = 3000
		result.Detected = true
		return result
	}

	// ── 8. Vite.config.[ts|js] + package.json deps ──────────────────────────.
	if fileExistsAny(dir, "vite.config.ts", "vite.config.js") {
		result.Type = "spa"
		result.BuildTool = "vite"
		result.Port = detectPortFromConfig(dir, "vite", 5173)
		result.Detected = true
		switch {
		case hasDep(earlyDeps, "react"):
			result.Framework = "react"
		case hasDep(earlyDeps, "vue"):
			result.Framework = "vue"
		case hasDep(earlyDeps, "svelte"):
			result.Framework = "svelte"
		default:
			result.Framework = "vanilla-javascript"
		}
		return result
	}

	// ── 9. Next.config.[js|ts|mjs] ─────────────────────────────────────────.
	if fileExistsAny(dir, "next.config.js", "next.config.ts", "next.config.mjs") {
		result.Framework = "nextjs"
		result.Type = "regular"
		result.Port = detectPortFromConfig(dir, "nextjs", 3000)
		result.Detected = true
		return result
	}

	// ── 10. Svelte.config.[js|ts] ────────────────────────────────────────────.
	if fileExistsAny(dir, "svelte.config.js", "svelte.config.ts") {
		result.Framework = "sveltekit"
		result.Type = "regular"
		result.BuildTool = detectBuildToolFromFiles(dir, "sveltekit")
		result.Port = detectPortFromConfig(dir, "sveltekit", 3000)
		result.Detected = true
		return result
	}

	// Create-expo-app has generated app.json (not expo.json) since SDK 46 (2022).
	// Check app.json first; fall back to expo.json for legacy projects.
	if isExpoProject(dir) || fileExists(dir, "expo.json") {
		result.Framework = "expo"
		result.Type = "native"
		result.Detected = true
		return result
	}

	// ── 12. .csproj ──────────────────────────────────────────────────────────.
	if content, ok := findCsprojContent(dir); ok {
		if fw, qsType, found := detectFromCsproj(content); found {
			result.Framework = fw
			result.Type = qsType
			if fw == "maui" || fw == "dotnet-mobile" {
				result.BundleID = readDotnetMobileBundleID(content)
			}
			result.Detected = true
			return result
		}
	}

	// ── 13. Android (native Java/Kotlin) — BEFORE Java build files ──────────.
	// AndroidManifest.xml is required by every Android project and is absent from
	// Java server-side apps. Checking it here prevents an Android project from
	// being misdetected as vanilla-java when build.gradle is present.
	// React Native projects also have app/src/main/AndroidManifest.xml in their
	// Android sub-project; guard against that by checking for the react-native dep.
	if fileExists(dir, filepath.Join("app", "src", "main", "AndroidManifest.xml")) && !hasDep(earlyDeps, "react-native") {
		result.Framework = "android"
		result.Type = "native"
		result.BuildTool = "gradle"
		result.BundleID = readAndroidApplicationID(dir)
		result.Detected = true
		return result
	}

	// ── 14. iOS Swift — xcodeproj directory or Package.swift ─────────────────.
	// Vapor (server-side Swift) also uses Package.swift. Guard against it by
	// checking for a Vapor dependency before classifying as ios-swift.
	if hasXcodeprojDir(dir) || (fileExists(dir, "Package.swift") && !isVaporSwiftPackage(dir)) {
		result.Framework = "ios-swift"
		result.Type = "native"
		result.BundleID = readIOSBundleID(dir)
		result.Detected = true
		return result
	}

	// ── 15. Pom.xml / build.gradle (Java) ────────────────────────────────────.
	if content, buildTool, ok := findJavaBuildContent(dir); ok {
		fw, port := detectJavaFramework(content)
		result.Framework = fw
		result.Type = "regular"
		result.BuildTool = buildTool
		result.Port = port
		result.Detected = true
		return result
	}

	// ── 16. Go.mod ──────────────────────────────────────────────────────────.
	if fileExists(dir, "go.mod") {
		result.Framework = "vanilla-go"
		result.Type = "regular"
		result.Detected = true
		return result
	}

	// ── 17. Gemfile (Ruby on Rails) ─────────────────────────────────────────.
	if data, ok := readFileContent(dir, "Gemfile"); ok {
		if strings.Contains(data, "rails") {
			result.Framework = "rails"
			result.Type = "regular"
			result.Port = 3000
			result.Detected = true
			return result
		}
	}

	// ── 18. Requirements.txt / pyproject.toml / Pipfile (Python) ───────────────.
	// Pipfile and Pipfile.lock are also checked so that Pipenv-based projects
	// (which have no requirements.txt) are detected correctly.
	for _, pyFile := range []string{"requirements.txt", "pyproject.toml", "Pipfile", "Pipfile.lock"} {
		if data, ok := readFileContent(dir, pyFile); ok {
			lower := strings.ToLower(data)
			if strings.Contains(lower, "flask") {
				result.Framework = "vanilla-python"
				result.Type = "regular"
				result.Port = 5000
				result.Detected = true
				return result
			}
			if strings.Contains(lower, "django") {
				result.Framework = "django"
				result.Type = "regular"
				result.Port = 8000
				result.Detected = true
				return result
			}
		}
	}

	// ── 19. Package.json dep scanning (lowest priority) ─────────────────────.
	// Note: Ionic deps are already handled above (step 1).
	if len(earlyDeps) > 0 {
		candidates := collectPackageJSONCandidates(earlyDeps)
		switch len(candidates) {
		case 1:
			c := candidates[0]
			result.Framework = c.framework
			result.Type = c.qsType
			result.BuildTool = c.buildTool
			result.Port = c.port
			result.Detected = true
			// React Native uses the same android/app/build.gradle structure as Flutter.
			if c.framework == "react-native" {
				result.BundleID = readMobileBundleID(dir)
			}
		default:
			if len(candidates) > 1 {
				result.Type = "regular" // All package.json web deps are regular/native.
				result.Detected = true
				// Use the common port if all candidates agree (e.g. express + hono both use 3000).
				commonPort := candidates[0].port
				for _, c := range candidates {
					if c.port != commonPort {
						commonPort = 0
						break
					}
				}
				result.Port = commonPort
				for _, c := range candidates {
					result.AmbiguousCandidates = append(result.AmbiguousCandidates, c.framework)
				}
			}
		}
	}

	return result
}

// collectPackageJSONCandidates returns all framework candidates found in deps.
func collectPackageJSONCandidates(deps map[string]bool) []detectionCandidate {
	var candidates []detectionCandidate
	if hasDep(deps, "@ionic/angular") {
		candidates = append(candidates, detectionCandidate{framework: "ionic-angular", qsType: "native"})
	}
	if hasDep(deps, "@ionic/react") {
		candidates = append(candidates, detectionCandidate{framework: "ionic-react", qsType: "native", buildTool: "vite"})
	}
	if hasDep(deps, "@ionic/vue") {
		candidates = append(candidates, detectionCandidate{framework: "ionic-vue", qsType: "native", buildTool: "vite"})
	}
	// React-native without expo (expo check would have matched earlier in DetectProject).
	if hasDep(deps, "react-native") {
		candidates = append(candidates, detectionCandidate{framework: "react-native", qsType: "native"})
	}
	if hasDep(deps, "express") {
		candidates = append(candidates, detectionCandidate{framework: "express", qsType: "regular", port: 3000})
	}
	if hasDep(deps, "hono") {
		candidates = append(candidates, detectionCandidate{framework: "hono", qsType: "regular", port: 3000})
	}
	if hasDep(deps, "fastify") {
		candidates = append(candidates, detectionCandidate{framework: "fastify", qsType: "regular", port: 3000})
	}
	return candidates
}

// detectFromCsproj returns framework and type from .csproj file content.
func detectFromCsproj(content string) (framework, qsType string, found bool) {
	switch {
	case strings.Contains(content, "Microsoft.AspNetCore.Components"):
		return "aspnet-blazor", "regular", true
	case strings.Contains(content, "Microsoft.Owin"):
		return "aspnet-owin", "regular", true
	case strings.Contains(content, "Microsoft.AspNetCore.Mvc"):
		return "aspnet-mvc", "regular", true
	// .NET 6+: MVC is built-in via Microsoft.NET.Sdk.Web — no PackageReference generated.
	// Check this after Blazor (AspNetCore.Components) and OWIN to avoid false positives.
	case strings.Contains(content, `Sdk="Microsoft.NET.Sdk.Web"`):
		return "aspnet-mvc", "regular", true
	case strings.Contains(content, "Microsoft.Maui"):
		return "maui", "native", true
	// A .csproj targeting a mobile TFM (net*-android or net*-ios) without a
	// Microsoft.Maui reference is a .NET Mobile (dotnet-mobile) project.
	// The regex requires the net<major>.<minor> prefix to avoid false positives
	// on package names or condition strings that contain bare "-ios"/"-android".
	case mobileTFMRegex.MatchString(content):
		return "dotnet-mobile", "native", true
	case strings.Contains(content, "-windows"):
		return "wpf-winforms", "native", true
	}
	return "", "", false
}

// detectJavaFramework returns the framework key and default port from Java build file content.
func detectJavaFramework(content string) (framework string, port int) {
	lower := strings.ToLower(content)
	switch {
	case strings.Contains(lower, "spring-boot"):
		return "spring-boot", 8080
	case strings.Contains(lower, "javax.ee") ||
		strings.Contains(lower, "jakarta.ee") ||
		strings.Contains(lower, "javax.servlet") ||
		strings.Contains(lower, "jakarta.servlet") ||
		// Jakarta.platform:jakarta.jakartaee-api is the standard BOM for Jakarta EE 9+.
		strings.Contains(lower, "jakarta.platform"):
		return "java-ee", 0
	default:
		return "vanilla-java", 0
	}
}

// Create-expo-app has generated app.json (not expo.json) since SDK 46 in 2022.
func isExpoProject(dir string) bool {
	data, err := os.ReadFile(filepath.Join(dir, "app.json"))
	if err != nil {
		return false
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return false
	}
	_, hasExpoKey := obj["expo"]
	return hasExpoKey
}

// readRawExpoScheme reads the "expo.scheme" field from app.json without validating it.
// Returns the raw string value (may be empty or invalid).
func readRawExpoScheme(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "app.json"))
	if err != nil {
		return ""
	}
	var obj struct {
		Expo struct {
			Scheme string `json:"scheme"`
		} `json:"expo"`
	}
	if err := json.Unmarshal(data, &obj); err != nil {
		return ""
	}
	return obj.Expo.Scheme
}

// readExpoScheme reads the "expo.scheme" field from app.json if present.
// The scheme is used as the custom URI prefix for EAS/production builds
// (e.g. "myapp" → callback URL "myapp://").
// Returns empty string if the field is absent, invalid per RFC 3986, or on any error.
func readExpoScheme(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "app.json"))
	if err != nil {
		return ""
	}
	var obj struct {
		Expo struct {
			Scheme string `json:"scheme"`
		} `json:"expo"`
	}
	if err := json.Unmarshal(data, &obj); err != nil {
		return ""
	}
	scheme := obj.Expo.Scheme
	if !isValidURIScheme(scheme) {
		return ""
	}
	return scheme
}

// scheme = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." ).
func isValidURIScheme(s string) bool {
	if len(s) == 0 {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')) {
				return false
			}
		} else {
			if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
				(r >= '0' && r <= '9') || r == '+' || r == '-' || r == '.') {
				return false
			}
		}
	}
	return true
}

// dirExists returns true if the named entry in dir is a directory.
func dirExists(dir, name string) bool {
	info, err := os.Stat(filepath.Join(dir, name))
	return err == nil && info.IsDir()
}

// fileExists returns true if the named file exists in dir.
func fileExists(dir, name string) bool {
	_, err := os.Stat(filepath.Join(dir, name))
	return err == nil
}

// fileExistsAny returns true if any of the named files exist in dir.
func fileExistsAny(dir string, names ...string) bool {
	for _, name := range names {
		if fileExists(dir, name) {
			return true
		}
	}
	return false
}

// readFileContent reads a file and returns its content as a string.
func readFileContent(dir, name string) (string, bool) {
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		return "", false
	}
	return string(data), true
}

// readPackageJSONDeps reads package.json and returns a set of all dependency names
// (from both "dependencies" and "devDependencies").
func readPackageJSONDeps(dir string) map[string]bool {
	data, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return nil
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return nil
	}
	deps := make(map[string]bool)
	for k := range pkg.Dependencies {
		deps[k] = true
	}
	for k := range pkg.DevDependencies {
		deps[k] = true
	}
	return deps
}

// readPackageJSONName reads the "name" field from package.json in dir.
// Returns empty string if not found or on any error.
func readPackageJSONName(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return ""
	}
	var pkg struct {
		Name string `json:"name"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return ""
	}
	return pkg.Name
}

// readProjectName tries to extract a meaningful project name from language-specific
// manifest files. It falls back to empty string if none are found; the caller then
// uses filepath.Base(dir).
func readProjectName(dir string) string {
	if name := readPackageJSONName(dir); name != "" {
		return name
	}
	if name := readGoModuleName(dir); name != "" {
		return name
	}
	if name := readPyprojectName(dir); name != "" {
		return name
	}
	if name := readPubspecName(dir); name != "" {
		return name
	}
	if name := readComposerName(dir); name != "" {
		return name
	}
	if name := readPomArtifactID(dir); name != "" {
		return name
	}
	return ""
}

// readGoModuleName reads the module path from go.mod and returns its last path segment.
func readGoModuleName(dir string) string {
	data, ok := readFileContent(dir, "go.mod")
	if !ok {
		return ""
	}
	for _, line := range strings.SplitN(data, "\n", 20) {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			modulePath := strings.TrimSpace(strings.TrimPrefix(line, "module "))
			return filepath.Base(modulePath)
		}
	}
	return ""
}

// readPyprojectName reads the project name from pyproject.toml ([project] or [tool.poetry] section).
func readPyprojectName(dir string) string {
	data, ok := readFileContent(dir, "pyproject.toml")
	if !ok {
		return ""
	}
	for _, line := range strings.Split(data, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "name ") && !strings.HasPrefix(line, "name=") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		val := strings.TrimSpace(parts[1])
		val = strings.Trim(val, `"'`)
		if val != "" {
			return val
		}
	}
	return ""
}

// readPubspecName reads the name field from pubspec.yaml.
func readPubspecName(dir string) string {
	data, ok := readFileContent(dir, "pubspec.yaml")
	if !ok {
		return ""
	}
	for _, line := range strings.Split(data, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "name:") {
			val := strings.TrimSpace(strings.TrimPrefix(trimmed, "name:"))
			if val != "" {
				return val
			}
		}
	}
	return ""
}

// readComposerName reads the package name from composer.json and returns the part after "/".
func readComposerName(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "composer.json"))
	if err != nil {
		return ""
	}
	var pkg struct {
		Name string `json:"name"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil || pkg.Name == "" {
		return ""
	}
	if idx := strings.LastIndex(pkg.Name, "/"); idx >= 0 {
		return pkg.Name[idx+1:]
	}
	return pkg.Name
}

// readPomArtifactID reads the first <artifactId> value from pom.xml.
func readPomArtifactID(dir string) string {
	data, ok := readFileContent(dir, "pom.xml")
	if !ok {
		return ""
	}
	const open = "<artifactId>"
	const closeTag = "</artifactId>"
	start := strings.Index(data, open)
	if start == -1 {
		return ""
	}
	start += len(open)
	end := strings.Index(data[start:], closeTag)
	if end == -1 {
		return ""
	}
	return strings.TrimSpace(data[start : start+end])
}

// hasDep returns true if the named dependency is in the deps set.
func hasDep(deps map[string]bool, name string) bool {
	return deps[name]
}

// findCsprojContent finds the first .csproj file in dir and returns its content.
func findCsprojContent(dir string) (string, bool) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".csproj") {
			if data, err := os.ReadFile(filepath.Join(dir, e.Name())); err == nil {
				return string(data), true
			}
		}
	}
	return "", false
}

// portPattern matches port assignments in config files, e.g. `port: 3001` or `"port": 3001`.
var portPattern = regexp.MustCompile(`"?port"?\s*:\s*(\d{4,5})`)

// mobileTFMRegex matches .NET mobile Target Framework Monikers (net*-android or net*-ios).
// A bare substring match on "-android" / "-ios" can produce false positives on package
// names such as "Newtonsoft.Json-ios" or condition attributes. Requiring the leading
// net<major>.<minor> prefix eliminates those false positives.
var mobileTFMRegex = regexp.MustCompile(`net\d+\.\d+-(?:android|ios)`)

// extractPortFromContent returns the first port number found in content, or 0 if none found.
func extractPortFromContent(content string) int {
	matches := portPattern.FindStringSubmatch(content)
	if len(matches) < 2 {
		return 0
	}
	p, err := strconv.Atoi(matches[1])
	if err != nil || p < 1024 || p > 65535 {
		return 0
	}
	return p
}

// detectPortFromConfig tries to read the port from a project config file.
// It checks framework-specific files (vite.config.ts/js for vite-based projects,
// angular.json for Angular, next.config.* for Next.js). Falls back to defaultPort.
func detectPortFromConfig(dir, hint string, defaultPort int) int {
	switch hint {
	case "angular":
		if data, ok := readFileContent(dir, "angular.json"); ok {
			if p := extractPortFromContent(data); p > 0 {
				return p
			}
		}
	case "nextjs":
		for _, name := range []string{"next.config.ts", "next.config.js", "next.config.mjs"} {
			if data, ok := readFileContent(dir, name); ok {
				if p := extractPortFromContent(data); p > 0 {
					return p
				}
			}
		}
	case "django", "rails", "vanilla-go", "vanilla-python", "aspnet-mvc", "aspnet-blazor",
		"aspnet-owin", "vanilla-php", "vanilla-java", "java-ee", "spring-boot", "laravel",
		"express", "hono", "fastify", "nuxt", "android", "ios-swift":
		// Backend-only or non-vite frameworks: no config file to inspect, use default directly.
	default:
		// For vite-based projects (react, vue, svelte, sveltekit, ionic-*, etc.)
		for _, name := range []string{"vite.config.ts", "vite.config.js"} {
			if data, ok := readFileContent(dir, name); ok {
				if p := extractPortFromContent(data); p > 0 {
					return p
				}
			}
		}
	}
	return defaultPort
}

// detectBuildToolFromFiles detects the build tool by checking for config files in dir.
// Falls back to the conventional default for the framework if no relevant file is found.
func detectBuildToolFromFiles(dir, framework string) string {
	if fileExistsAny(dir, "vite.config.ts", "vite.config.js") {
		return "vite"
	}
	if fileExists(dir, "pom.xml") {
		return "maven"
	}
	if fileExistsAny(dir, "build.gradle", "build.gradle.kts") {
		return "gradle"
	}
	if fileExists(dir, "composer.json") {
		return "composer"
	}
	// Framework-specific defaults as fallback.
	switch framework {
	case "ionic-react", "ionic-vue", "sveltekit":
		return "vite"
	case "spring-boot", "vanilla-java", "java-ee":
		return "maven"
	case "laravel", "vanilla-php":
		return "composer"
	}
	return ""
}

// findJavaBuildContent finds pom.xml or build.gradle and returns content + build tool name.
func findJavaBuildContent(dir string) (content, buildTool string, ok bool) {
	if data, err := os.ReadFile(filepath.Join(dir, "pom.xml")); err == nil {
		return string(data), "maven", true
	}
	if data, err := os.ReadFile(filepath.Join(dir, "build.gradle")); err == nil {
		return string(data), "gradle", true
	}
	if data, err := os.ReadFile(filepath.Join(dir, "build.gradle.kts")); err == nil {
		return string(data), "gradle", true
	}
	return "", "", false
}

// readMobileBundleID reads the application ID for Flutter and React Native projects.
// It first checks android/app/build.gradle (applicationId). For iOS-only projects
// (no android/ directory or no applicationId found), it falls back to reading
// ios/Runner.xcodeproj/project.pbxproj (PRODUCT_BUNDLE_IDENTIFIER) and then
// ios/Runner/Info.plist (CFBundleIdentifier, if not a build variable reference).
//
// Note: when both Android and iOS are present, the Android applicationId is returned
// for both platform callback URL patterns. In practice these identifiers usually match,
// but they can differ for projects that set them independently — in that case the user
// should update the Auth0 Dashboard callback URLs manually.
func readMobileBundleID(dir string) string {
	if data, err := os.ReadFile(filepath.Join(dir, "android", "app", "build.gradle")); err == nil {
		if id := extractGradleApplicationID(string(data)); id != "" {
			return id
		}
	}
	// IOS fallback: try project.pbxproj first (the canonical source for the bundle ID),
	// then Info.plist (only when CFBundleIdentifier is not a build variable reference).
	return readIOSBundleID(dir)
}

// readIOSBundleID reads the bundle identifier from iOS project files.
// It checks, in order:
//  1. ios/Runner.xcodeproj/project.pbxproj (Flutter path)
//  2. Any root-level *.xcodeproj/project.pbxproj (native Xcode projects)
//  3. ios/Runner/Info.plist (Flutter fallback)
//
// Returns empty string if no concrete (non-variable) bundle ID is found.
func readIOSBundleID(dir string) string {
	// Flutter path.
	if data, err := os.ReadFile(filepath.Join(dir, "ios", "Runner.xcodeproj", "project.pbxproj")); err == nil {
		if id := extractPbxprojBundleID(string(data)); id != "" {
			return id
		}
	}
	// Native Xcode projects place the .xcodeproj at the root of the repo.
	if entries, err := os.ReadDir(dir); err == nil {
		for _, e := range entries {
			if e.IsDir() && strings.HasSuffix(e.Name(), ".xcodeproj") {
				pbx := filepath.Join(dir, e.Name(), "project.pbxproj")
				if data, err := os.ReadFile(pbx); err == nil {
					if id := extractPbxprojBundleID(string(data)); id != "" {
						return id
					}
				}
			}
		}
	}
	if data, err := os.ReadFile(filepath.Join(dir, "ios", "Runner", "Info.plist")); err == nil {
		if id := extractInfoPlistBundleID(string(data)); id != "" {
			return id
		}
	}
	return ""
}

// pbxprojBundleIDRegex matches PRODUCT_BUNDLE_IDENTIFIER = com.example.app; in project.pbxproj.
var pbxprojBundleIDRegex = regexp.MustCompile(`PRODUCT_BUNDLE_IDENTIFIER\s*=\s*([a-zA-Z][a-zA-Z0-9._-]*)\s*;`)

// extractPbxprojBundleID extracts the app target's PRODUCT_BUNDLE_IDENTIFIER from
// project.pbxproj content. It iterates all occurrences and skips test-target bundle
// IDs (those ending in .Tests, .RunnerTests, or .UITests), which typically appear
// before the app target in the file. Returns empty string if no app-target ID is found.
func extractPbxprojBundleID(content string) string {
	all := pbxprojBundleIDRegex.FindAllStringSubmatch(content, -1)
	for _, m := range all {
		if len(m) < 2 {
			continue
		}
		id := strings.TrimSpace(m[1])
		// Skip test-target bundle IDs. In Xcode-generated project.pbxproj files,
		// test targets appear before the app target. Both dotted suffixes
		// (com.example.app.Tests, com.example.app.UITests) and concatenated
		// suffixes (com.example.appTests) all end in "Tests".
		if strings.HasSuffix(id, "Tests") {
			continue
		}
		return id
	}
	return ""
}

// infoPlistBundleIDRegex matches <key>CFBundleIdentifier</key> followed by <string>value</string>.
var infoPlistBundleIDRegex = regexp.MustCompile(`<key>CFBundleIdentifier</key>\s*<string>([^<]+)</string>`)

// extractInfoPlistBundleID extracts CFBundleIdentifier from Info.plist content.
// Returns empty string if absent or if the value is an Xcode build variable reference
// (e.g. "$(PRODUCT_BUNDLE_IDENTIFIER)").
func extractInfoPlistBundleID(content string) string {
	matches := infoPlistBundleIDRegex.FindStringSubmatch(content)
	if len(matches) < 2 {
		return ""
	}
	id := strings.TrimSpace(matches[1])
	// Skip Xcode variable references such as "$(PRODUCT_BUNDLE_IDENTIFIER)".
	if strings.Contains(id, "$") {
		return ""
	}
	return id
}

// gradleAppIDRegex matches applicationId in build.gradle files.
// Supports both double-quoted ("com.example.app") and single-quoted ('com.example.app')
// forms (Groovy DSL), as well as the Kotlin DSL assignment form
// applicationId = "com.example.app".
var gradleAppIDRegex = regexp.MustCompile(`applicationId\s*=?\s*["']([a-zA-Z][a-zA-Z0-9._-]*)["']`)

// extractGradleApplicationID extracts the applicationId value from build.gradle content.
func extractGradleApplicationID(content string) string {
	matches := gradleAppIDRegex.FindStringSubmatch(content)
	if len(matches) < 2 {
		return ""
	}
	return matches[1]
}

// capacitorTSAppIDRegex extracts the appId value from capacitor.config.ts.
// Matches both single-quoted and double-quoted values.
var capacitorTSAppIDRegex = regexp.MustCompile(`appId\s*:\s*['"]([^'"]+)['"]`)

// readCapacitorAppID reads the "appId" field from capacitor.config.json or
// capacitor.config.ts in dir. Capacitor v3+ defaults to the TypeScript config.
// Returns empty string if neither file is present or the field is missing.
func readCapacitorAppID(dir string) string {
	// Try JSON config first (Capacitor v2 and v3+ both support it).
	if data, err := os.ReadFile(filepath.Join(dir, "capacitor.config.json")); err == nil {
		var cfg struct {
			AppID string `json:"appId"`
		}
		if jsonErr := json.Unmarshal(data, &cfg); jsonErr == nil && cfg.AppID != "" {
			return cfg.AppID
		}
	}
	// Fall back to TypeScript config (Capacitor v3+ default).
	// Process line-by-line to skip comment lines that may contain an appId value
	// (e.g. "// appId: 'old.value'") which would otherwise be matched first.
	if data, err := os.ReadFile(filepath.Join(dir, "capacitor.config.ts")); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if strings.HasPrefix(strings.TrimSpace(line), "//") {
				continue
			}
			if m := capacitorTSAppIDRegex.FindStringSubmatch(line); len(m) >= 2 {
				return m[1]
			}
		}
	}
	return ""
}

// readDotnetMobileBundleID extracts the <ApplicationId> element from .csproj content.
// Used for MAUI and .NET Mobile apps to generate callback URL guidance.
// Returns empty string if the element is absent.
func readDotnetMobileBundleID(content string) string {
	matches := csprojAppIDRegex.FindStringSubmatch(content)
	if len(matches) < 2 {
		return ""
	}
	return strings.TrimSpace(matches[1])
}

// csprojAppIDRegex matches the <ApplicationId> element in a .csproj file.
var csprojAppIDRegex = regexp.MustCompile(`<ApplicationId>\s*([a-zA-Z][a-zA-Z0-9._-]*)\s*</ApplicationId>`)

// isVaporSwiftPackage returns true if Package.swift in dir contains a Vapor dependency.
// Vapor's Package.swift references "vapor/vapor.git" or the package URL contains "vapor/vapor".
func isVaporSwiftPackage(dir string) bool {
	data, ok := readFileContent(dir, "Package.swift")
	if !ok {
		return false
	}
	return strings.Contains(data, "vapor/vapor")
}

// hasXcodeprojDir returns true if any directory entry in dir ends with ".xcodeproj".
// An .xcodeproj bundle is the primary signal file for Xcode-based iOS/macOS Swift projects.
func hasXcodeprojDir(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() && strings.HasSuffix(e.Name(), ".xcodeproj") {
			return true
		}
	}
	return false
}

// readAndroidApplicationID reads the applicationId from app/build.gradle or app/build.gradle.kts.
func readAndroidApplicationID(dir string) string {
	for _, name := range []string{
		filepath.Join("app", "build.gradle"),
		filepath.Join("app", "build.gradle.kts"),
	} {
		if data, err := os.ReadFile(filepath.Join(dir, name)); err == nil {
			if id := extractGradleApplicationID(string(data)); id != "" {
				return id
			}
		}
	}
	return ""
}

// detectionFriendlyAppType returns a concise label for the detection summary display.
func detectionFriendlyAppType(qsType string) string {
	switch qsType {
	case "spa":
		return "Single Page App"
	case "regular":
		return "Regular Web App"
	case "native":
		return "Native / Mobile"
	case "m2m":
		return "Machine to Machine"
	default:
		return qsType
	}
}
