Output create-user-assign-role.gif

Set FontSize 24
Set Width 1200
Set Height 600

#---
Type "auth0 users create"
Sleep 500ms
Enter
Sleep 750ms
Enter
Sleep 500ms


Type "Poovam"
Sleep 500ms
Enter
Sleep 500ms

Type "poovam@travel0.com"
Sleep 500ms
Enter
Sleep 500ms

Type "secure-pass123!"
Sleep 500ms
Enter
Sleep 2500ms


Type "auth0 users search"
Sleep 750ms
Enter
Sleep 500ms
Type "*"
Sleep 500ms
Enter
Sleep 4000ms