// Code generated by MockGen. DO NOT EDIT.
// Source: connection.go

// Package auth0 is a generated GoMock package.
package auth0

import (
	gomock "github.com/golang/mock/gomock"
	management "gopkg.in/auth0.v5/management"
	reflect "reflect"
)

// MockConnectionAPI is a mock of ConnectionAPI interface
type MockConnectionAPI struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionAPIMockRecorder
}

// MockConnectionAPIMockRecorder is the mock recorder for MockConnectionAPI
type MockConnectionAPIMockRecorder struct {
	mock *MockConnectionAPI
}

// NewMockConnectionAPI creates a new mock instance
func NewMockConnectionAPI(ctrl *gomock.Controller) *MockConnectionAPI {
	mock := &MockConnectionAPI{ctrl: ctrl}
	mock.recorder = &MockConnectionAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConnectionAPI) EXPECT() *MockConnectionAPIMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockConnectionAPI) Create(c *management.Connection, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{c}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockConnectionAPIMockRecorder) Create(c interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{c}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConnectionAPI)(nil).Create), varargs...)
}

// Read mocks base method
func (m *MockConnectionAPI) Read(id string, opts ...management.RequestOption) (*management.Connection, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(*management.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockConnectionAPIMockRecorder) Read(id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockConnectionAPI)(nil).Read), varargs...)
}

// List mocks base method
func (m *MockConnectionAPI) List(opts ...management.RequestOption) (*management.ConnectionList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*management.ConnectionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockConnectionAPIMockRecorder) List(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConnectionAPI)(nil).List), opts...)
}

// Update mocks base method
func (m *MockConnectionAPI) Update(id string, c *management.Connection, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{id, c}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockConnectionAPIMockRecorder) Update(id, c interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id, c}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConnectionAPI)(nil).Update), varargs...)
}

// Delete mocks base method
func (m *MockConnectionAPI) Delete(id string, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockConnectionAPIMockRecorder) Delete(id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectionAPI)(nil).Delete), varargs...)
}

// ReadByName mocks base method
func (m *MockConnectionAPI) ReadByName(name string, opts ...management.RequestOption) (*management.Connection, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadByName", varargs...)
	ret0, _ := ret[0].(*management.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByName indicates an expected call of ReadByName
func (mr *MockConnectionAPIMockRecorder) ReadByName(name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByName", reflect.TypeOf((*MockConnectionAPI)(nil).ReadByName), varargs...)
}
