// Code generated by MockGen. DO NOT EDIT.
// Source: log_stream.go

// Package auth0 is a generated GoMock package.
package auth0

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	management "gopkg.in/auth0.v5/management"
)

// MockLogStreamAPI is a mock of LogStreamAPI interface.
type MockLogStreamAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLogStreamAPIMockRecorder
}

// MockLogStreamAPIMockRecorder is the mock recorder for MockLogStreamAPI.
type MockLogStreamAPIMockRecorder struct {
	mock *MockLogStreamAPI
}

// NewMockLogStreamAPI creates a new mock instance.
func NewMockLogStreamAPI(ctrl *gomock.Controller) *MockLogStreamAPI {
	mock := &MockLogStreamAPI{ctrl: ctrl}
	mock.recorder = &MockLogStreamAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStreamAPI) EXPECT() *MockLogStreamAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLogStreamAPI) Create(ls *management.LogStream, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ls}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLogStreamAPIMockRecorder) Create(ls interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ls}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLogStreamAPI)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockLogStreamAPI) Delete(id string, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLogStreamAPIMockRecorder) Delete(id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLogStreamAPI)(nil).Delete), varargs...)
}

// List mocks base method.
func (m *MockLogStreamAPI) List(opts ...management.RequestOption) ([]*management.LogStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*management.LogStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLogStreamAPIMockRecorder) List(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLogStreamAPI)(nil).List), opts...)
}

// Read mocks base method.
func (m *MockLogStreamAPI) Read(id string, opts ...management.RequestOption) (*management.LogStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(*management.LogStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockLogStreamAPIMockRecorder) Read(id interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockLogStreamAPI)(nil).Read), varargs...)
}

// Update mocks base method.
func (m *MockLogStreamAPI) Update(id string, ls *management.LogStream, opts ...management.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{id, ls}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLogStreamAPIMockRecorder) Update(id, ls interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id, ls}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLogStreamAPI)(nil).Update), varargs...)
}
